// <auto-generated />
using System;
using EarlyWarning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EarlyWarning.Migrations
{
    [DbContext(typeof(EarlyWarningDbContext))]
    [Migration("20260509235434_grainPriceModel")]
    partial class grainPriceModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EarlyWarning.Models.Aid.AssistanceRecipient", b =>
                {
                    b.Property<Guid>("AssistanceRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FemaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("FemaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("FemaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("FemaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("FemaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("FemaleYouth")
                        .HasColumnType("int");

                    b.Property<int>("MaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("MaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("MaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("MaleYouth")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssistanceRecipientId");

                    b.HasIndex("WoredaId");

                    b.ToTable("AssistanceRecipients");
                });

            modelBuilder.Entity("EarlyWarning.Models.Aid.OtherProblem", b =>
                {
                    b.Property<Guid>("OtherProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FemaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("FemaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("FemaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("FemaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("FemaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("FemaleYouth")
                        .HasColumnType("int");

                    b.Property<string>("GeneralNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("HasOtherProblem")
                        .HasColumnType("bit");

                    b.Property<int>("MaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("MaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("MaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("MaleYouth")
                        .HasColumnType("int");

                    b.Property<string>("ProblemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OtherProblemId");

                    b.HasIndex("WoredaId");

                    b.ToTable("OtherProblems");
                });

            modelBuilder.Entity("EarlyWarning.Models.Aid.SupplyType", b =>
                {
                    b.Property<Guid>("SupplyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SupplyTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplyTypeId");

                    b.ToTable("SupplyTypes");
                });

            modelBuilder.Entity("EarlyWarning.Models.Aid.WeeklyProvided", b =>
                {
                    b.Property<Guid>("WeeklyProvidedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DistributedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Donor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IfProblem")
                        .HasColumnType("int");

                    b.Property<int>("Measurement")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PercentageOfDistributedFromProvided")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProvidedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SupplyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WeeklyProvidedId");

                    b.HasIndex("SupplyTypeId");

                    b.HasIndex("WoredaId");

                    b.ToTable("WeeklyProvideds");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalPrice", b =>
                {
                    b.Property<Guid>("AnimalPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrainSupplyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnimalPriceId");

                    b.HasIndex("WoredaId");

                    b.ToTable("AnimalPrice");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalPriceDetail", b =>
                {
                    b.Property<Guid>("AnimalPriceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalPriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalPriceIncreaseDecreaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AnimalPriceDetailId");

                    b.HasIndex("AnimalPriceId");

                    b.HasIndex("AnimalPriceIncreaseDecreaseId");

                    b.ToTable("AnimalPriceDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalPriceIncreaseDecrease", b =>
                {
                    b.Property<Guid>("AnimalPriceIncreaseDecreaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReasonType")
                        .HasColumnType("int");

                    b.HasKey("AnimalPriceIncreaseDecreaseId");

                    b.ToTable("AnimalPriceIncreaseDecreases");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalPricePerUnit", b =>
                {
                    b.Property<Guid>("GrainPricePerQuintalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrainTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceDifference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeeklyMarketStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GrainPricePerQuintalId");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("GrainTypeId");

                    b.HasIndex("WoredaId");

                    b.ToTable("AnimalPricePerUnits");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalType", b =>
                {
                    b.Property<Guid>("AnimalTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnimalTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AnimalTypeId");

                    b.ToTable("AnimalTypes");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalSupply.AnimalIncreaseDecrease", b =>
                {
                    b.Property<Guid>("AnimalIncreaseDecreaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReasonType")
                        .HasColumnType("int");

                    b.HasKey("AnimalIncreaseDecreaseId");

                    b.ToTable("AnimalIncreaseDecreases");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalSupply.AnimalSupply", b =>
                {
                    b.Property<Guid>("GrainSupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrainSupplyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GrainSupplyId");

                    b.HasIndex("WoredaId");

                    b.ToTable("AnimalSupplys");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalSupply.AnimalSupplyDetail", b =>
                {
                    b.Property<Guid>("AnimalSupplyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalIncreaseDecreaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalSupplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AnimalSupplyDetailId");

                    b.HasIndex("AnimalIncreaseDecreaseId");

                    b.HasIndex("AnimalSupplyId");

                    b.ToTable("AnimalSupplyDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDisease", b =>
                {
                    b.Property<Guid>("EpidemicDiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FemaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("FemaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("FemaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("FemaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("FemaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("FemaleYouth")
                        .HasColumnType("int");

                    b.Property<bool>("HasEpidemicDisease")
                        .HasColumnType("bit");

                    b.Property<int>("LactatingMothers")
                        .HasColumnType("int");

                    b.Property<int>("MaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("MaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("MaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("MaleYouth")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NumberOfAffectedKebeles")
                        .HasColumnType("int");

                    b.Property<int>("PregnantWomen")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EpidemicDiseaseId");

                    b.HasIndex("WoredaId");

                    b.ToTable("EpidemicDiseases");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseKebele", b =>
                {
                    b.Property<Guid>("EpidemicDiseaseKebeleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EpidemicDiseaseReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KebeleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EpidemicDiseaseKebeleId");

                    b.HasIndex("EpidemicDiseaseReportId");

                    b.HasIndex("KebeleId");

                    b.ToTable("EpidemicDiseaseKebeles");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseSelection", b =>
                {
                    b.Property<Guid>("EpidemicDiseaseSelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EpidemicDiseaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EpidemicDiseaseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EpidemicDiseaseTypeId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EpidemicDiseaseSelectionId");

                    b.HasIndex("EpidemicDiseaseId");

                    b.HasIndex("EpidemicDiseaseTypeId");

                    b.HasIndex("EpidemicDiseaseTypeId1");

                    b.ToTable("EpidemicDiseaseSelections");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseType", b =>
                {
                    b.Property<Guid>("EpidemicDiseaseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EpidemicDiseaseTypeId");

                    b.ToTable("EpidemicDiseaseTypes");
                });

            modelBuilder.Entity("EarlyWarning.Models.HumanDrinkWaterIssue.HumanDrinkWaterIssue", b =>
                {
                    b.Property<Guid>("HumanDrinkWaterIssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AffectedKebeleIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FemaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("FemaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("FemaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("FemaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("FemaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("FemaleYouth")
                        .HasColumnType("int");

                    b.Property<bool>("HasWaterProblem")
                        .HasColumnType("bit");

                    b.Property<int>("MaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("MaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("MaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("MaleYouth")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfAffectedKebeles")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HumanDrinkWaterIssueId");

                    b.HasIndex("WoredaId");

                    b.ToTable("HumanDrinkWaterIssues");
                });

            modelBuilder.Entity("EarlyWarning.Models.HumanDrinkWaterIssue.HumanDrinkWaterKebele", b =>
                {
                    b.Property<Guid>("HumanDrinkWaterKebeleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HumanDrinkWaterIssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KebeleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HumanDrinkWaterKebeleId");

                    b.HasIndex("HumanDrinkWaterIssueId");

                    b.HasIndex("KebeleId");

                    b.ToTable("HumanDrinkWaterKebeles");
                });

            modelBuilder.Entity("EarlyWarning.Models.Locations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardHeaderTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HumanDrinkWaterIssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LasModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LocationAmharicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HumanDrinkWaterIssueId");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CardHeaderTitle = "National HQ",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LasModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 0,
                            LocationAmharicName = "ኢትዮጵያ",
                            LocationCode = "ETH",
                            LocationName = "Ethiopia",
                            PhoneNumber = "+251-111-111111"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CardHeaderTitle = "City Administration",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LasModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 1,
                            LocationAmharicName = "አዲስ አበባ",
                            LocationCode = "ETH-ADD",
                            LocationName = "Addis Ababa",
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PhoneNumber = "+251-111-222222"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CardHeaderTitle = "Kirkos District",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LasModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 3,
                            LocationAmharicName = "ቂርቆስ",
                            LocationCode = "ETH-ADD-KIR",
                            LocationName = "Kirkos",
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PhoneNumber = "+251-111-333333"
                        });
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.Death", b =>
                {
                    b.Property<Guid>("DeathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasDeath")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeathId");

                    b.HasIndex("WoredaId");

                    b.ToTable("Deaths");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.DeathDetail", b =>
                {
                    b.Property<Guid>("DeathDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeathId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeathReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FemaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("FemaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("FemaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("FemaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("FemaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("FemaleYouth")
                        .HasColumnType("int");

                    b.Property<int>("MaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("MaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("MaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("MaleYouth")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DeathDetailId");

                    b.HasIndex("DeathId");

                    b.ToTable("DeathDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.Migration", b =>
                {
                    b.Property<Guid>("MigrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("HasMigration")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MigrationId");

                    b.HasIndex("WoredaId");

                    b.ToTable("Migrations");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.MigrationDetail", b =>
                {
                    b.Property<Guid>("MigrationDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FemaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("FemaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("FemaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("FemaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("FemaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("FemaleYouth")
                        .HasColumnType("int");

                    b.Property<int>("MaleChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaleDisabled")
                        .HasColumnType("int");

                    b.Property<int>("MaleElderly")
                        .HasColumnType("int");

                    b.Property<int>("MaleFamilyMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaleHouseholdHeads")
                        .HasColumnType("int");

                    b.Property<int>("MaleYouth")
                        .HasColumnType("int");

                    b.Property<Guid>("MigrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MigrationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("MigrationReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OriginLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MigrationDetailId");

                    b.HasIndex("MigrationReportId");

                    b.HasIndex("OriginLocationId");

                    b.ToTable("MigrationDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.PasswordResetKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetKeys");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPrice", b =>
                {
                    b.Property<Guid>("GrainPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrainSupplyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GrainPriceId");

                    b.HasIndex("WoredaId");

                    b.ToTable("GrainPrices");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPriceDetail", b =>
                {
                    b.Property<Guid>("GrainPriceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrainPriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrainPriceIncreaseDecreaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("GrainPriceDetailId");

                    b.HasIndex("GrainPriceId");

                    b.HasIndex("GrainPriceIncreaseDecreaseId");

                    b.ToTable("GrainPriceDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPriceIncreaseDecrease", b =>
                {
                    b.Property<Guid>("GrainIncreaseDecreaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReasonType")
                        .HasColumnType("int");

                    b.HasKey("GrainIncreaseDecreaseId");

                    b.ToTable("GrainPriceIncreaseDecreases");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPricePerQuintal", b =>
                {
                    b.Property<Guid>("GrainPricePerQuintalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrainTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceDifference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeeklyMarketStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GrainPricePerQuintalId");

                    b.HasIndex("GrainTypeId");

                    b.HasIndex("WoredaId");

                    b.ToTable("GrainPricePerQuintals");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainType", b =>
                {
                    b.Property<Guid>("GrainTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GrainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GrainTypeId");

                    b.ToTable("GrainTypes");
                });

            modelBuilder.Entity("EarlyWarning.Models.SupplyofGrain.GrainIncreaseDecrease", b =>
                {
                    b.Property<Guid>("GrainIncreaseDecreaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReasonType")
                        .HasColumnType("int");

                    b.HasKey("GrainIncreaseDecreaseId");

                    b.ToTable("GrainIncreaseDecreases");
                });

            modelBuilder.Entity("EarlyWarning.Models.SupplyofGrain.GrainSupply", b =>
                {
                    b.Property<Guid>("GrainSupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrainSupplyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GrainSupplyId");

                    b.HasIndex("WoredaId");

                    b.ToTable("GrainSupplys");
                });

            modelBuilder.Entity("EarlyWarning.Models.SupplyofGrain.GrainSupplyDetail", b =>
                {
                    b.Property<Guid>("GrainSupplyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrainIncreaseDecreaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrainSupplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("GrainSupplyDetailId");

                    b.HasIndex("GrainIncreaseDecreaseId");

                    b.HasIndex("GrainSupplyId");

                    b.ToTable("GrainSupplyDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.WeeklyAccidents.AccidentDetail", b =>
                {
                    b.Property<Guid>("AccidentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccidentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AffectedChildrenFemale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedChildrenMale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedDisabledFemale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedDisabledMale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedElderlyFemale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedElderlyMale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedHouseholdsFemale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedHouseholdsMale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedYouthFemale")
                        .HasColumnType("int");

                    b.Property<int>("AffectedYouthMale")
                        .HasColumnType("int");

                    b.Property<decimal?>("DamageRateInPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DamagedLandInHectares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("WeeklyAccidentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccidentDetailId");

                    b.HasIndex("AccidentTypeId");

                    b.HasIndex("WeeklyAccidentsId");

                    b.ToTable("AccidentDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.WeeklyAccidents.AccidentType", b =>
                {
                    b.Property<Guid>("AccidentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccidentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AccidentTypeId");

                    b.ToTable("AccidentTypes");
                });

            modelBuilder.Entity("EarlyWarning.Models.WeeklyAccidents.WeeklyAccidents", b =>
                {
                    b.Property<Guid>("WeeklyAccidentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccidentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasAccident")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WoredaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WeeklyAccidentsId");

                    b.HasIndex("AccidentTypeId");

                    b.HasIndex("WoredaId");

                    b.ToTable("WeeklyAccidents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EarlyWarning.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserLocationLevl")
                        .HasColumnType("int");

                    b.Property<int>("UsernameChangeLimit")
                        .HasColumnType("int");

                    b.HasIndex("LocationId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("EarlyWarning.Models.Aid.AssistanceRecipient", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.Aid.OtherProblem", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.Aid.WeeklyProvided", b =>
                {
                    b.HasOne("EarlyWarning.Models.Aid.SupplyType", null)
                        .WithMany("WeeklyProvided")
                        .HasForeignKey("SupplyTypeId");

                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalPrice", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalPriceDetail", b =>
                {
                    b.HasOne("EarlyWarning.Models.AnimalPrice.AnimalPrice", "AnimalPrice")
                        .WithMany()
                        .HasForeignKey("AnimalPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.AnimalPrice.AnimalPriceIncreaseDecrease", "AnimalPriceIncreaseDecrease")
                        .WithMany()
                        .HasForeignKey("AnimalPriceIncreaseDecreaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalPrice");

                    b.Navigation("AnimalPriceIncreaseDecrease");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalPricePerUnit", b =>
                {
                    b.HasOne("EarlyWarning.Models.AnimalPrice.AnimalType", null)
                        .WithMany("AnimalPrices")
                        .HasForeignKey("AnimalTypeId");

                    b.HasOne("EarlyWarning.Models.PriceofGrain.GrainType", "GrainType")
                        .WithMany()
                        .HasForeignKey("GrainTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrainType");

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalSupply.AnimalSupply", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalSupply.AnimalSupplyDetail", b =>
                {
                    b.HasOne("EarlyWarning.Models.AnimalSupply.AnimalIncreaseDecrease", "AnimalIncreaseDecrease")
                        .WithMany()
                        .HasForeignKey("AnimalIncreaseDecreaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.AnimalSupply.AnimalSupply", "AnimalSupply")
                        .WithMany("AnimalSupplyDetails")
                        .HasForeignKey("AnimalSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalIncreaseDecrease");

                    b.Navigation("AnimalSupply");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDisease", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseKebele", b =>
                {
                    b.HasOne("EarlyWarning.Models.EpidemicDisease.EpidemicDisease", "EpidemicDisease")
                        .WithMany("EpidemicDiseaseKebeles")
                        .HasForeignKey("EpidemicDiseaseReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.Locations", "Kebele")
                        .WithMany()
                        .HasForeignKey("KebeleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EpidemicDisease");

                    b.Navigation("Kebele");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseSelection", b =>
                {
                    b.HasOne("EarlyWarning.Models.EpidemicDisease.EpidemicDisease", "EpidemicDisease")
                        .WithMany("EpidemicDiseaseSelections")
                        .HasForeignKey("EpidemicDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseType", "EpidemicDiseaseType")
                        .WithMany()
                        .HasForeignKey("EpidemicDiseaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseType", null)
                        .WithMany("EpidemicDiseaseSelections")
                        .HasForeignKey("EpidemicDiseaseTypeId1");

                    b.Navigation("EpidemicDisease");

                    b.Navigation("EpidemicDiseaseType");
                });

            modelBuilder.Entity("EarlyWarning.Models.HumanDrinkWaterIssue.HumanDrinkWaterIssue", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.HumanDrinkWaterIssue.HumanDrinkWaterKebele", b =>
                {
                    b.HasOne("EarlyWarning.Models.HumanDrinkWaterIssue.HumanDrinkWaterIssue", "HumanDrinkWaterIssues")
                        .WithMany("HumanDrinkWaterKebeles")
                        .HasForeignKey("HumanDrinkWaterIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.Locations", "Kebele")
                        .WithMany()
                        .HasForeignKey("KebeleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanDrinkWaterIssues");

                    b.Navigation("Kebele");
                });

            modelBuilder.Entity("EarlyWarning.Models.Locations", b =>
                {
                    b.HasOne("EarlyWarning.Models.HumanDrinkWaterIssue.HumanDrinkWaterIssue", null)
                        .WithMany("AffectedKebeles")
                        .HasForeignKey("HumanDrinkWaterIssueId");

                    b.HasOne("EarlyWarning.Models.Locations", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.Death", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.DeathDetail", b =>
                {
                    b.HasOne("EarlyWarning.Models.Migration.Death", "Death")
                        .WithMany("DeathDetails")
                        .HasForeignKey("DeathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Death");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.Migration", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.MigrationDetail", b =>
                {
                    b.HasOne("EarlyWarning.Models.Migration.Migration", "Migration")
                        .WithMany("MigrationDetails")
                        .HasForeignKey("MigrationReportId");

                    b.HasOne("EarlyWarning.Models.Locations", "OriginLocation")
                        .WithMany()
                        .HasForeignKey("OriginLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Migration");

                    b.Navigation("OriginLocation");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPrice", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPriceDetail", b =>
                {
                    b.HasOne("EarlyWarning.Models.PriceofGrain.GrainPrice", "GrainPrice")
                        .WithMany("GrainPriceDetails")
                        .HasForeignKey("GrainPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.PriceofGrain.GrainPriceIncreaseDecrease", "GrainPriceIncreaseDecrease")
                        .WithMany()
                        .HasForeignKey("GrainPriceIncreaseDecreaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrainPrice");

                    b.Navigation("GrainPriceIncreaseDecrease");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPricePerQuintal", b =>
                {
                    b.HasOne("EarlyWarning.Models.PriceofGrain.GrainType", "GrainType")
                        .WithMany("GrainPrices")
                        .HasForeignKey("GrainTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrainType");

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.SupplyofGrain.GrainSupply", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("EarlyWarning.Models.SupplyofGrain.GrainSupplyDetail", b =>
                {
                    b.HasOne("EarlyWarning.Models.SupplyofGrain.GrainIncreaseDecrease", "GrainIncreaseDecrease")
                        .WithMany()
                        .HasForeignKey("GrainIncreaseDecreaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.SupplyofGrain.GrainSupply", "GrainSupply")
                        .WithMany("GrainSupplyDetails")
                        .HasForeignKey("GrainSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrainIncreaseDecrease");

                    b.Navigation("GrainSupply");
                });

            modelBuilder.Entity("EarlyWarning.Models.WeeklyAccidents.AccidentDetail", b =>
                {
                    b.HasOne("EarlyWarning.Models.WeeklyAccidents.AccidentType", "AccidentType")
                        .WithMany()
                        .HasForeignKey("AccidentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlyWarning.Models.WeeklyAccidents.WeeklyAccidents", "WeeklyAccidents")
                        .WithMany("AccidentDetails")
                        .HasForeignKey("WeeklyAccidentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccidentType");

                    b.Navigation("WeeklyAccidents");
                });

            modelBuilder.Entity("EarlyWarning.Models.WeeklyAccidents.WeeklyAccidents", b =>
                {
                    b.HasOne("EarlyWarning.Models.WeeklyAccidents.AccidentType", null)
                        .WithMany("WeeklyAccidents")
                        .HasForeignKey("AccidentTypeId");

                    b.HasOne("EarlyWarning.Models.Locations", "Woreda")
                        .WithMany()
                        .HasForeignKey("WoredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woreda");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EarlyWarning.Models.ApplicationUser", b =>
                {
                    b.HasOne("EarlyWarning.Models.Locations", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EarlyWarning.Models.Aid.SupplyType", b =>
                {
                    b.Navigation("WeeklyProvided");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalPrice.AnimalType", b =>
                {
                    b.Navigation("AnimalPrices");
                });

            modelBuilder.Entity("EarlyWarning.Models.AnimalSupply.AnimalSupply", b =>
                {
                    b.Navigation("AnimalSupplyDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDisease", b =>
                {
                    b.Navigation("EpidemicDiseaseKebeles");

                    b.Navigation("EpidemicDiseaseSelections");
                });

            modelBuilder.Entity("EarlyWarning.Models.EpidemicDisease.EpidemicDiseaseType", b =>
                {
                    b.Navigation("EpidemicDiseaseSelections");
                });

            modelBuilder.Entity("EarlyWarning.Models.HumanDrinkWaterIssue.HumanDrinkWaterIssue", b =>
                {
                    b.Navigation("AffectedKebeles");

                    b.Navigation("HumanDrinkWaterKebeles");
                });

            modelBuilder.Entity("EarlyWarning.Models.Locations", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.Death", b =>
                {
                    b.Navigation("DeathDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.Migration.Migration", b =>
                {
                    b.Navigation("MigrationDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainPrice", b =>
                {
                    b.Navigation("GrainPriceDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.PriceofGrain.GrainType", b =>
                {
                    b.Navigation("GrainPrices");
                });

            modelBuilder.Entity("EarlyWarning.Models.SupplyofGrain.GrainSupply", b =>
                {
                    b.Navigation("GrainSupplyDetails");
                });

            modelBuilder.Entity("EarlyWarning.Models.WeeklyAccidents.AccidentType", b =>
                {
                    b.Navigation("WeeklyAccidents");
                });

            modelBuilder.Entity("EarlyWarning.Models.WeeklyAccidents.WeeklyAccidents", b =>
                {
                    b.Navigation("AccidentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
